<?xml version="1.0" encoding="utf-8"?>

<xsl:stylesheet version="1.0"
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="OI">

    <xsl:if test="normalize-space(OI03)">
      <tr>
        <td class="label">Benefits Assignment Certification Indicator: </td>
        <td class="data1">
          <xsl:choose>
            <xsl:when test="OI03 = 'N'">No</xsl:when>
            <xsl:when test="OI03 = 'W'">Not Applicable</xsl:when>
            <xsl:when test="OI03 = 'Y'">Yes</xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="OI03"/>
            </xsl:otherwise>
          </xsl:choose>
        </td>
      </tr>
    </xsl:if>

    <xsl:if test="normalize-space(OI04)">
      <tr>
        <td class="label">Benefits Assignment Certification Indicator: </td>
        <td class="data1">
          <xsl:choose>
            <xsl:when test="OI04 = 'P'">Signature generated by provider because the patient was not physically present for services</xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="OI04"/>
            </xsl:otherwise>
          </xsl:choose>
        </td>
      </tr>
    </xsl:if>

    <xsl:if test="normalize-space(OI06)">
      <tr>
        <td class="label">Release of Information Code: </td>
        <td class="data1">
          <xsl:choose>
            <xsl:when test="OI06 = 'I'">Informed Consent to Release Medical Information for Conditions or Diagnosises Regulated by Federal Statues</xsl:when>
            <xsl:when test="OI06 = 'Y'">Yes, Provider as a Signed Statement Permitting Release of Medical Billing Data Related to a Claim</xsl:when>
            <xsl:otherwise>
              <xsl:value-of select="OI06"/>
            </xsl:otherwise>
          </xsl:choose>
        </td>
      </tr>
    </xsl:if>
  </xsl:template>

</xsl:stylesheet>
